#!/usr/bin/env python
# coding=utf-8

from matplotlib import pyplot as plt
from matplotlib import animation
import getpss


fig = plt.figure()
ax1 = fig.add_subplot(2,1,1,xlim=(0, 100), ylim=(0, 350))
ax2 = fig.add_subplot(2,1,2,xlim=(0, 100), ylim=(0, 100))
line, = ax1.plot([], [], lw=2)
line2, = ax2.plot([], [], lw=2)
x = []
y= []
y2 = []
def init():
    line.set_data([], [])
    line.set_data([], [])
    return line,line2
def getx():
    t = "0"
    return t

def animate(i):
    x.append(int(getx())+i)
    y.append(int(getpss.getTotalPss())/1024)
    y2.append(getpss.getCpu())
    print x,y
    line.set_data(x,y)
    line2.set_data(x,y2)
    return line,line2

anim1 = animation.FuncAnimation(fig, animate, init_func=init,  frames=1000, interval=30)
plt.show()
#getpss.writ_pss(str(y),1)